### ISSUE TITLE
Reasons behind K-mer superiority

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#106]
Hi Yoav,

I hope everything is fine. 
I have few questions of which I did not find adequate reasonings in your paper.

1. Why do some K-mers shows higher p-values passing the significance threshold whereas SNPs in the same region failed to pass the threshold? Is it because K-mers might have a higher effect size than SNPs, which allows them to pass the significance threshold? 
2. As you said before that every significant SNP should be recovered by K-mers, how do you explain the scenario when significant SNPs are not tagged by significant K-mers? Could it be because some SNPs associations might be spurious?

It would be nice to get your feedback on these issues.

Thank you.

Regards
Anik

**Comment by voichek** [comment]
Hi Anik,

1. I think there are two things to consider. First, like SNPs, two variants which are close-by on the genome might get a different p-value, and you usually get only for a small fraction of SNPs/k-mers in a specific region of the genome the most significant p-values. The LD is not complete even in small regions. Second, as we also discuss a bit in the paper, sometime you will have a k-mer which tags a SNP but still get a more significant p-value than the SNP it tags. I think this is due to the process of SNP calling, where you have to put some thresholds to get a nice set of SNPs to work with (e.g. threshold on mapping quality, number of reads supporting each genotype) or imputing SNPs which can have an even stronger effect. Therefore, you might loose some of the statistical power when you are doing associations. For the example of flowering time in Arabidopsis I looked specifically at this and I saw that in the SNP calling procedure, missing values were called in some of the accessions. However when I looked manually I saw that the k-mers identified the right calling and the algorithm was too stringent.
2. This can be due to the more stringent threshold for significant put on k-mers, we discussed this in the paper: " _For 137 phenotypes, only a significant SNP could be identified, likely due to the more stringent thresholds for k-mers, as the most significant SNPs rarely passed the k-mer threshold in these cases (Fig. 2d). Moreover, a k-mer passing the SNP threshold was in high LD with the top SNP (Fig. 2e)."_

Hope it helps,
Yoav

**Comment by DuttaAnik** [comment]
Hi Yoav,
Thanks a lot for this clarification. Yeah, it makes complete sense then.

Cheers
Anik
