### ISSUE TITLE
Why the kmers can't be filtered at the second step in permutaion?

### ISSUE THREAD

**Issue by laserhsu** [voichek/kmersGWAS#107]
Dear Voichek,
Tks for ur great work. 
I have run this pipeline for many phenotypes in multiple environments, but there exists a problem.
For some environments, in last step for gemma GWAS I can't filtered the kmers successfully. I still have 10000 kmers (in kmer/pass_threshold_5per file) same as the result after first step (kmer/output/phenotype_value.assoc.txt).
So i wondered may be someghing wrong with the threshold? How  can I solve this problem?
Looking forward to your reply.

Sincerely,
Xu Han.

**Comment by voichek** [comment]
Dear Xu Han,

Can it be that all the k-mers in `kmer/output/phenotype_value.assoc.txt` pass the 5% threshold?

Best,
Yoav

**Comment by voichek** [comment]
Hi,

First I would increase the number of k-mers passing the first filter by a lot. You can do this using the `--kmers_number` options or using the `--kmers_for_no_perm_phenotype` (this second option is to increase the number of k-mers for the phenotype but not for the permutation, as there you only need the most significant p-value).

Second, maybe, as you get so many k-mers passing the threshold, you can run the full model on all the k-mers in your k-mer table. This mostly depends on how many k-mers you have in your table and if it reasonable computationally. This will let you plot a QQ-plot which be useful to asses inflation in p-values.

Best,
Yoav

**Comment by laserhsu** [comment]
Dear Voichek,
Tks 4 your kindly reply again~
I see the QQplot of my data, and it inflated indeed. 
If using the same threshold I got from the first run, there is more than 20k significant _k_-mers. Is this result normal? and no other methods to further restrict the number？

Sincerely,
Xu Han

**Comment by voichek** [comment]
Dear Xu Han,

Regarding the high number of k-mers, I think you can further try to understand what is going on by looking at the pattern of correlation (LD) between the different k-mers presence/absence patterns, then you can see if it is one phenomena or many.

You should try to understand why you have inflation, it might be due to population structure that are not fully accounted for by the kinship (maybe a SNP based kinship matrix works better?). The other option is some covariate, unfortunately for now I didn't implemented a covariate into this package (though I think it is possible and not to complicated if someone wants to try).

Best,
Yoav

**Comment by laserhsu** [comment]
Dear Yoav Voichek,

So clear explaination!

Best,
Xu han
