### ISSUE TITLE
kmer size 61

### ISSUE THREAD

**Issue by zsdxgl** [voichek/kmersGWAS#124]
Hi,

Why the kmer size is defined between 10 and 31. If I want to use size 61, how to modify the code? Thanks

Leon

**Comment by voichek** [comment]
Dear Leon,

I am afraid there is no easy fix for increasing the _k-mer_ size above 31. The code is highly optimized to use the CPU word size which is 64bits. 

I do think _k-mers_ of size 31 should be able to catch almost everything that a 61 _k-mer_ will catch, and will be more immune to sequencing errors and close variants being inside the same _k-mer_. 

Best,
Yoav

**Comment by zsdxgl** [comment]
Dear Yoav,

Thanks very much. Actually, I have to agree with you. Uniq kmer will be captured by kmer=31. But others, not uniq may can caputed by larger kmer, even though sequence error may disturb the results. Consindering the sequencing error is low enough, increasing kmer would benefit these lost kmers.

If, only if, I want to increase kmer, the code will need rewritter largely. Acutally, I am more familar with perl than C++/C.  Any suggestion?

Best wishes,
Leon

**Comment by voichek** [comment]
Dear Leon,

If you want to get into the nitty-gritty of the code, there are two ways I can think to modify it

1. To change the data structure to give 2 words per k-mer, this will give you 128 bits --> up to 63 bp k-mer + 2 bit fo flags. You will need to change the data structure of how k-mers are saved in the kmers_table and how they are stored in the different data structures in the code.
2. You can make a patch, which might be easier to program - by indexing the k-mers instead of representing their full sequence. That is, before the k-mers go into the program from the KMC databases give each one a running index and when you have the results in the end of the GWAS convert them back to the original sequences. 

These two options require either extensive study of the current code or efficient c++ coding for the second. If you do go for it, let me know how did it go.

Another option, if you want k-mers larger than 31 is to use the methodology from [Gaurav et al](https://www.nature.com/articles/s41587-021-01058-4). I haven't tried it myself, but it worked well for them.

Good luck,
Yoav

**Comment by zsdxgl** [comment]
Dear Yoav,

Great ideas.  Thanks for the options. Actually,  my aim is to find the specific markers, the groups specific kmers can be obtained by manipulating the kmers by KMC. Then the common kmers between each individual and the kmers pools can be obtained by "intersect". Until then, the data size would be small and can compare between the control and case easily. The seqeuencing error and the group specific kmers can be compromised by adjusting kmer length.

If the aim can't be obtained by above thought, then I will try your options.

Best,
Leon
