### ISSUE TITLE
How can I make a manhaton plot!

### ISSUE THREAD

**Issue by sunnycqcn** [voichek/kmersGWAS#14]
Hello,
Much appreciated for your suggestions and excellent tool.
I have got the assocation results. How can I make a manhaton plot and LD plot based on the kmer association results. I sas you have presented on your paper.
Best,
Fuyou

**Comment by voichek** [comment]
1. **Manhattan plot** - for this you need to have the genomic location of your identified _k_-mers. Doing this is is not part of this library. Briefly, the easiest approach can be to map the _k_-mers to the genome, this might work for some of the _k_-mers. However, you might have problems mapping due to the short length of the _k_-mers, and also for the more interesting cases like associations not part of the genome or SV. The next thing you can do is to find the reads from which the _k_-mers originated and map them. You can read more on the technicalities of how we plotted the associations with flowering time in our method. Just to emphasize, this method is most interesting when you won't be able to place your associations on the genome.
2. **LD** - to calculate LD between _k_-mers you just need the population presence/absence patterns of your associated _k_-mers.  You can get those by using the `/bin/filter_kmers` functionality. Then you can use any LD measure.
