### ISSUE TITLE
Results differ between kmersGWAS and GEMMA run separately on kmers produced earlier in the pipeline

### ISSUE THREAD

**Issue by tommydavies** [voichek/kmersGWAS#142]
Hey there, 

Thanks for the build. Worked quite well for me and I have learned a lot. However, one question: 

I have run the kmersGWAS, and I have also converted the kmer table to PLINK format so that I could conduct a GWAS using GEMMA outside of the kmersGWAS pipeline (to create QQ plot, plot Allele Freq, pvals, etc.). Upon comparing the results from the kmersGWAS pipeline and that of the entire GEMMA run independently, the top results do not match. For example, the top kmer from the kmersGWAS is a different kmer, and has a higher pvalue than the top kmer from running an independent GEMMA model. 

I ran the independent GEMMA model with the same kinship matrix, and all flags set to the same as inside kemrsGWAS. 

Is there any reasoning/explanation as to why the top results are different between the two? Please forgive me if there is an obvious explanation I am missing, but I feel I have investigated the kmersGWAS build and cannot find an explanation. 

Any help would be appreciated. 

Thanks, 
Tommy

**Comment by voichek** [comment]
Dear Tommy,

I'm pleased to know that you've had a positive experience with our library.

To address your observation, it's indeed unexpected for there to be discrepancies in the top k-mers between the two methods. Both the kmersGWAS pipeline and running an independent GEMMA model should ideally yield similar top results. If there's a difference in the most significant k-mer, it has to be more significant in testing the full set with GEMMA, not the other way, as you describe. This is due to the two-step filtering strategies, which sometime can miss a k-mer.

When I tested the method I've checked this in a few cases and I've never observed what you describe. Moreover, from how it is built the behaviour should not happened. My best guess, having no other information, is that some of the parameters in running the GWAS with GEMMA are not exactly the same (as the k-mers-pipeline also run GEMMA).

You can send me the full dataset and I can check it for you, but: it is usually huge files and I am going on a vacation tomorrow for two weeks, so maybe you can try to identify the issue. I would suggest to just take the highest k-mer which is identified in the pipeline and try to see what happened to it in the full GEMMA run. There is two likely scenarios: (1) it doesn't get a score in the running the full model because of some filtering in the GEMMA (likely low MAC/MAF) (2) it gets a different score which might be due to the kinship being different or the exact parameters. 

Another way to track what happened is to run the pipeline with `--dont_remove_intermediates` which will leave in the output folder the files to run in GEMMA so you can run the GEMMA exactly as it was run in the pipeline (the log file should have the GEMMA run command line), and see you get the same results. You can also compare from the plink binary format the variation in the population of this top k-mer and see if it the same as in your full plink binary file.

Hope it helps,
if not I will be able to help more when I am back,
Best,
Yoav

**Comment by tommydavies** [comment]
Hey Yoav, 

Yes, this has helped. After diving into your kmersGWAS code base, I realized that the reason I was not getting the same results when using GEMMA separately was because I was not using the `--miss 0.5` GEMMA flag that is used in the kmersGWAS. Once I re-ran GEMMA with this flag, it reproduced the results from kmersGWAS. 

However, I am curious about the use of this flag (--miss 0.5 in the GEMMA model) for the kmersGWAS, and hoping you can provide some clarity. If kmers from each sample are encoded as presence or absence (0/1), how can kmers be "missing" from some samples? Would they not be encoded as 0's if not detected, and therefor no kmers in the set would be "missing"? For example, if a kmer is not detected in 25/100 samples, then those 25 samples would have 0's for those kmers; they would not be encoded as "missing" the kmers (correct?). How can any sample have "missing" kmers if all kmers are encoded as binary presence/absence? I hope this question makes sense. I can email you or provide more clarity to the question if need be. 

I have read (and re-read!) the publication, but can't a section rationalizing the use of this flag. 

If you provide any clarity here it would be appreciated. I am sure some others would benefit from understanding all the parameters used for thorough publication purposes. 

Thanks a lot for your time, and I hope you enjoyed your vacation! 
Tommy

**Comment by voichek** [comment]
Dear Tommy,

I agree, I see no reason to add this flag for the k-mers, which are never missing. I think this flag is added so the command to run GWAS on SNPs, which can be missing, and on k-mers will be exactly the same. I tried to remember if there is any other reasoning for adding this flag but I don't remember any.

I would be happy to see the an example of a k-mers plink binary file that produce different results only by changing the "-miss" value. Can you send me the k-mers plink binary the pass the first filtering in the k-mers-GWAS with the other files needed to run GEMMA (you will have them if you run with `--dont_remove_intermediates` and it shouldn't be a file which is too large).

Another simple check that you can do, is to try to extract from the plink binary file only the most significant k-mer which is lost when you run the GEMMA yourself, and output it in textual format? Does it have missing values, if it does then something is clearly wrong, otherwise it is something in GEMMA or the way you run the GEMMA.

Best,
Yoav

**Comment by tommydavies** [comment]
Hey Yoav. 

Thanks for this reply. I am going to take a hard look and use some of the suggestions you provided to try to get a better answer here. I will post my findings here shortly. 

Thanks, 
Tommy

**Comment by voichek** [comment]
Hi Tommy,

Can we close this issue for now, and if still relevant we will reopen it?

Best,
Yoav

**Comment by tommydavies** [comment]
Sure. Im still working through, and if need be, I will reopen the issue.

Thanks for the attention,
Tommy
________________________________
