### ISSUE TITLE
Very few pass_threshold_10per and pass_threshold_10per

### ISSUE THREAD

**Issue by nirwan1265** [voichek/kmersGWAS#144]
I have ~1X illumina sequences. I have BC2F4 population. So not your typical mapping population. I ran all the steps as in the example with 31 kmers. 
I am getting very few hits for thresshold passing the second filter:
> wc -l pass_threshold_10per pass_threshold_5per pheno.0.phenotype_value.bim
4 pass_threshold_10per
1 pass_threshold_5per
 100000 pheno.0.phenotype_value.bim
 100005 total
> more pass_threshold_10per
chr	rs	ps	n_miss	allele1	allele0	af	l_mle	p_lrt
0	AGGAATAGAAAATAAAAAGAAAAGACCAAAA_1	0	0	0	1	0.942	1.587941e+00	3.880805e-10
0	CCCAAGAGGACTGCATTACCGCCAGGCAGGC_9	0	0	0	1	0.066	2.607521e+00	3.075238e-10
0	GGAATAGAAAATAAAAAGAAAAGACCAAAAA_2	0	0	0	1	0.940	1.617496e+00	4.515657e-10

Is this normal for low seq depth?

**Comment by voichek** [comment]
Dear Nirwan,

It's nice to see you are trying the library on new types of data, but this also means that I don't have experience with this setup to offer much help.  

In general I would say that low coverage data would create many cases where you have wrong missing data, as it is because of the coverage and not because it was really missing. One thing you need to make sure is that when you create the k-mers table you put the filter in the KMC to k-mers appearing once and not twice because otherwise you will loose all you data (this will also add a lot of sequence errors into your table, but I don't think you have a choice). If you still get the k-mer and you have a way to follow up on it, it might be real.

In general it is very hard for this k-mer approach to work with low coverage data, so it might also be that this is not the right approach to take.

Hope it helps,
Yoav

**Comment by nirwan1265** [comment]
Thank you. I will try that. I am hoping it works and if I get good hits I will update the thread.
