### ISSUE TITLE
kmers_gwas.py

### ISSUE THREAD

**Issue by zc-li** [voichek/kmersGWAS#148]
Hello, I have a question about the output files in the program kmers_gwas.py.

The file "kmers/output/phenotype_value.assoc.txt.gz" does not contain all the GEMMA results. It only includes the GEMMA results for all k-mers that have passing the first filtering of the pipeline. What is the reason for this?

Then, I generated the QQ plot using the file "kmers/output/phenotype_value.assoc.txt.gz" and obtained the following graph, far from ideal. I would like to know how you obtained the QQ plot mentioned in your research paper.

Best wishes,
zcli

![qq](https://github.com/voichek/kmersGWAS/assets/95906125/267d3aa5-fbcd-484e-b57f-3d3852fd3c36)

**Comment by voichek** [comment]
Dear Zcli,

Thank you for your interest in our library.

As we explain in the manual and in the manuscript, the idea of the two-step filtering is to save computation and not to calculate the exact p-value for all k-mers. GEMMA runs only on the k-mers that pass the first filtering. Therefore, it makes sense that your QQ plot would look like this, since you are only looking at the most abundant k-mers.

If you want to do a QQ plot, you have to run the all model on all k-mers. As I explain in the manual, this can be done by converting the presence/absence matrix to a plink binary format and running the full model on it. 

Best,
Yoav
