### ISSUE TITLE
Non-canon kmers vs Non-canon kmers found

### ISSUE THREAD

**Issue by afrances1** [voichek/kmersGWAS#158]
Apologies if this is a question that might seem obvious, I am new to working with this pipeline and kmers in general. In the output generated by the kmers_add_strand_information step, the first 3 metrics generated are canonized kmers, non-canonized kmers, and non-canonized kmers found. What is the difference in how the latter two metrics are calculated, and is it expected for them to be different (ex. 1555480330 and 1259571659, respectively)?

Thanks, 
AF

**Comment by voichek** [comment]
Hi AF,

Before running `kmers_add_strand_information, the KMC tool is executed twice:

1. **Canonized counting**: This step counts the canonized k-mers (where the k-mer and its reverse complement are treated as identical) with a specified threshold (e.g., k-mers appearing at least 2 times).

2. **Non-canonized counting**: This step counts all non-canonized k-mers (treating each k-mer and its reverse complement as distinct), without applying any threshold.

The first metric, "canonized k-mers," reflects the total number of k-mers that passed the threshold during the canonized counting step. The second metric, "non-canonized k-mers," represents the total number of k-mers counted in the non-canonized step. The third metric, "non-canonized k-mers found," indicates the subset of non-canonized k-mers that correspond to the canonized k-mers (i.e., those that passed the threshold in the first step).

It's expected for the second and third numbers to differ because not all non-canonized k-mers will have a corresponding canonized k-mer, since the canonized counting step applies a threshold that the non-canonized step does not.

I hope this explanation clears things up. Feel free to close the issue if it does.
Best regards,
Yoav

**Comment by afrances1** [comment]
Yes that answers my question perfectly, thank you!
