### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by qazwsx1995** [voichek/kmersGWAS#20]
Create merger
terminate called after throwing an instance of 'std::logic_error'
  what():  sorted kmer file is empty: /home/example_dir/kmers_to_use

**Comment by voichek** [comment]
Hi,

Can you please give more details, which command did you run that gave you this massage.

It indicates that the  /home/example_dir/kmers_to_use is empty, is this true? if so I guess something went wrong in a previous step. Can you please indicate what commands you run to create the kmers_to_use file? are your individual kmers files empty as well?

Yoav

**Comment by voichek** [comment]
BTW, did you run example 2 with the e-coli dataset? This is a good check that you write the commands correctly and that there is no problem with the library in your specific setup.

**Comment by qazwsx1995** [comment]
> BTW, did you run example 2 with the e-coli dataset? This is a good check that you write the commands correctly and that there is no problem with the library in your specific setup.
right,i run run example 2 with the e-coli dataset ,but using the first 4 individual.every steps
 from the manual.pdf

**Comment by qazwsx1995** [comment]
previous step running well ,but when i export “kmers_to_use”,finding the result like this :
kmers lower than MAC:	0
passed kmers:	0
passed MAC bot not pass strand filter:	0

**Comment by voichek** [comment]
Hi,

I can not help with you providing more information:
1. Can you please indicate what exact commands you run to create the kmers_to_use file? are your individual kmers files empty as well?
2. Please run example 2 with the e coli data, this example should work.


This problem is likely one of the two: 1. input parameters that filtered all the k-mers or you didn't build the separate k-mers list correctly. Are the separate files empty as well? are you sure the paths are correct?

**Comment by voichek** [comment]
I am just wondering, on how many individuals are you trying to build the _k_-mers table? Maybe you have less than 5 and you still use the original filtering parameters that requires _k_-mers to appear in at least 5 individuals?
