### ISSUE TITLE
kmer-GWAS

### ISSUE THREAD

**Issue by duhuipeng** [voichek/kmersGWAS#33]
dear author
yesterday asked you why this chromosome is all 0, you said because there was no comparison with the reference genome, my idea now is to extract the kmer from the picture I showed you yesterday, then compare it with the reference genome, find his chromosome position, I also have the p value of each kmer, and then do the correlation analysis with the gemma, do you feel this method is ok? Where do you have txt text of this kmer translated into fa or fq code sources if feasible? I don't know how to convert

**Comment by voichek** [comment]
I am not sure what you mean by "correlation analysis with the gemma".

And yes, identifying the position of all k-mers and then plotting the k-mers-based manhattan plot might work. The problem is if you have problem finding the k-mers positions on the genome, or if they are not found in the reference at all. You can see examples in Figure 3 and 5 in our manuscript.
