### ISSUE TITLE
error for kmers_add_strand_information step

### ISSUE THREAD

**Issue by clementmo** [voichek/kmersGWAS#40]
Hi, Dear Voichek ,
Thank you for your excelent work about k-mers GWAS. I am learnning and try to do analysis following your manual. 
**First KMC:**
`../external_programs/kmc_v3 -t2 -k31 -ci2 @small_input_files.txt output_kmc_canon ./ 1> kmc_canon.1 2> kmc_canon.2`
two files were generated:  **output_kmc_canon.kmc_pre**,  **output_kmc_canon.kmc_suf**
**Second KMC:**
`../external_programs/kmc_v3 -t2 -k31 -ci0 -b @small_input_files.txt output_kmc_all ./ 1> kmc_all.1 2> kmc_all.2`
two files were generated: **output_kmc_all.kmc_pre**, **output_kmc_all.kmc_suf**  

After running
`../bin/kmers_add_strand_information -c output_kmc_canon -n output_kmc_all -k 31 -o kmers_with_strand`
**Error: flag 00 should be equal to zero.
 This is likely due to running the KMC non-canonized with -ci not 1**

This made me confused that the setting parameter is "-ci0" for the non-canonized KMC step. How did the error occured? Looking forward to your reply.
Thanks!

Best wishes,
Clement

**Comment by voichek** [comment]
Dear Clement,

Thank you for your interest in our work.

The error you are getting is a bit surprising to me.
First, the error message should be "...non-canonized with -ci not **0**", I will fix it.

Just to make sure, you are running on 64-bit system, right?

Best,
Yoav

**Comment by clementmo** [comment]
Hi Yoav，

Thank your for your quick reply. The error message is what I showed above.
My system is 64-bit .

Best wishes,
Clement

**Comment by voichek** [comment]
Can you please paste here the log from the two KMC runs and from the kmers_add_strand_information before it fell.

**Comment by clementmo** [comment]
Hi Yoav,
Thank you for your patience!
The file **12063501.out** is log for LSF system. The  file **kmc_canon.1** for the first KMC step was deleted by mistake. 

For the second KMC run, LSF system log is **12065133.out**. KMC log is **kmc_all.1**.

For the combination step, LSF system logs are **12150348.err** and **12150348.out**. There is no output for KMC.

All the mentioned files are attached.
Thank you again for your help.

Best wishes,
Clement

[12063501.out.txt](https://github.com/voichek/kmersGWAS/files/4749434/12063501.out.txt)

[12065133.out.txt](https://github.com/voichek/kmersGWAS/files/4749453/12065133.out.txt)
[kmc_all.1.txt](https://github.com/voichek/kmersGWAS/files/4749436/kmc_all.1.txt)

[12150348.err.txt](https://github.com/voichek/kmersGWAS/files/4749437/12150348.err.txt)
[12150348.out.txt](https://github.com/voichek/kmersGWAS/files/4749439/12150348.out.txt)

**Comment by voichek** [comment]
I am missing kmc_canon.1.txt, can you add it?

**Comment by voichek** [comment]
I see you said it was deleted, maybe a better option is to share the fastq files and the kmc files so I can recreate the error here. I will delete the data once we find the problem. Is this possible?

**Comment by clementmo** [comment]
Hi Yoav,
I rerun the first KMC and generated the kmc_canon.1.txt file that is attached. 
[kmc_canon.1.txt](https://github.com/voichek/kmersGWAS/files/4751959/kmc_canon.1.txt)

The first two steps are OK. The generated files of the first two steps are little large and I am compresising them. You can help to check **kmc_canon.1.txt** and judge wether I should send you the files. Thanks a lot.

**Comment by voichek** [comment]
Dear Clement,

Thanks for sending kmc_canon.1.txt.

It is not clear where the problem is coming from, although the two first steps didn't produce an error it does not mean that the output is valid. The problem is that it finds k-mers found in the canon k-mers count but not in the non-canon, which should not happen. This can be due to one of three options: 
1) My program which connect the two KMC file has a bug.
2) The KMC counting has a bug.
3) You mistakenly inputted things in the wrong way. 

Due to the low relative number of k-mers which are found in the canon but not in the non-canon counting I suspect it is not option (3) but rather (1) or (2). Another option is that one of the programs don't work properly specifically in your system. To check this I need your kmc files as well as the original sequencing file.

I never had this issue before, although I run this on thousands of samples, but I have never worked with a library as large as yours, so maybe something breaks with this huge library.  

Will it be possible to share this files with me? we can continue the technical detail of sharing over email (yoav.voichek at gmi.oeaw.ac.at)

Yoav
