### ISSUE TITLE
Issues with running kmerGWAS.py

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [voichek/kmersGWAS#61]
Hi Voicheck,
We are trying to get the pipeline running on our own data after everything went smooth on the e.coli resistance example. It is a bit tricky to set it up on the own data as errors are a bit difficult to track at times.

Right now we get the following error right at the start of kmers_gwas.py.

Error in read.table(file = file, header = header, sep = sep, quote = quote,  :
  no lines available in input
Calls: as.matrix -> read.csv -> read.table
Execution halted
Traceback (most recent call last):
  File "/home/ben/anaconda3/envs/kmersGWAS/bin/kmers_gwas.py", line 279, in <module>
    main()
  File "/home/ben/anaconda3/envs/kmersGWAS/bin/kmers_gwas.py", line 108, in main
    phenotypes_names = file(paths["pheno_permuted_fn"] ,"r").read().split("\n")[0].split("\t")[1:]
IOError: [Errno 2] No such file or directory: 'kmerGWASben/pheno.phenotypes_and_permutations'

In the output folder both pheno.phenotypes and pheno.kinship are empty even though the kindship table and phenotypes exits with following filenames Mac2P0.1.kmers_table.kinship and XX_phenoTable/XX_phenotype_values.tsv.

I have the felling there might be some explicit naming conventions going on that generates issues with parsing files.

Can you please help. Thanks!

**Comment by voichek** [comment]
Dear Benjamin,

I completely agree regarding the errors, it is in the first line in my to-do list regarding this project. I am new to building libraries for other people, and I hope i will free my time to fix the error handling (and a few other small stuff).

It seems to be a problem with the kinship (which can be due to missing phenotype file as well).

Can you please copy to here the line you used to run the pipeline?

It will also be helpful if you could share the phenotype file and the kmers_table.names and kmers_table.kinship files (here or to my mail). 

Best wishes,
Yoav

**Comment by voichek** [comment]
Maybe the names of accessions/strains is written a bit differently in the kmers_table.names and in the phenotype file?

**Comment by chrometam11** [comment]
Dear Voichek,

I am following up this issue. Thank you for pointing that out, I found that the paths and accessions in kmers_lists_path.txt are in the wrong format. I have fixed this and we are currently re-running the table. We will let you know if we come across more problems on the way. Thank you very much!

Best wishes,
Rita

**Comment by voichek** [comment]
Dear Rita,

Hope it will go smoothly from this point, thanks for letting me know.

Best,
Yoav

**Comment by BenjaminSchwessinger** [comment]
Thank you very much Voav. Your pointers help us figuring the error. Much appreciated.

Now we are keen getting it all run to the end.

Pretty excited.
________________________________
