### ISSUE TITLE
QQ-plot comparison between K-mer and SNP GWAS approach

### ISSUE THREAD

**Issue by DuttaAnik** [voichek/kmersGWAS#89]
Hi Yoav,
As promised before, I have added the QQ-plot from both the K-mer and SNP GWAS. It looks good to me. The QQ-plot on the left is from K-mer GWAS and QQ-plot from the SNP GWAS on the right. The SNP GWAS was ran using GAPIT MLM + Kinship.
It is interesting to see such a dramatic change between the two approaches. I wonder why would it happen. Could it be a difference in the thresholds due to differences in the underlying model in the two approaches?

Cheers
Anik
<img width="993" alt="Screen Shot 2021-04-21 at 13 10 50" src="https://user-images.githubusercontent.com/41111038/115545321-f644b900-a2a3-11eb-9a29-c4a853376d03.png">

**Comment by DuttaAnik** [comment]
Hi Yoav,
Yes, I agree with you. Actually, I checked for each of the significant K-mers where they are located in the genome. Surprisingly, in most cases, the most significant K-mers for each trait tagged a Transposable element family in the genome. There is a nice distribution of significant K-mers tagging a TE family and also many significant K-mers are found inside the gene. However, for few genes, I aligned the K-mers along with the gene and the corresponding blasted sequence from each individual. I expected to see if the K-mers tagged any Structural variants e.g. indels or not. But in most cases, I see that there are SNP polymorphisms that the K-mers tagging.

**Comment by voichek** [comment]
Hi Anik,

TE are for sure a case where k-mers can catch things SNPs couldn't. Could you pinpoint why the SNPs that the k-mer tag didn't give the same association? Is there a correlation between the k-mer presence absence and the SNP state?

Another trick which you can try to play with is to use the k-mer presence/absence as a phenotype in SNPs GWAS, then due to LD you might find the position in the genome.

Best,
Yoav

**Comment by DuttaAnik** [comment]
Hi Yoav,
Pinpoint: This is where I am at a loss. I really can't help myself to think of a reason why the SNPs did not pass the Bonferroni threshold in the normal GWAS. I tried to find a discussion in your paper where you had the K-mer superiority but did not get any clear answer to that.

Correlation: Do you mean to find the individuals with the k-mer present and then see whether they also carry the SNP or not?

K-mer presence/absence as phenotype: Yes, this is one possibility that I am planning to explore. But in the case of 100 significant K-mers, I will have to use each of them individually, right? Because each K-mer can be treated as a trait and its presence/absence pattern as a phenotypic value.

**Comment by voichek** [comment]
Dear Anik,

I don't think the issue is the threshold per se. In cases where I had such cases for example there were a lot of missing SNPs due to mappability issues or threshold in the SNP calling algorithms. I would just take some test case and look at the mapping in many accessions and compare it manually to the k-mer presence absence, and try to solve what happened in this specific location. If a k-mer just capture a SNP variant the SNP should pop-up even more strongly, at least theoretically.

Correlation, look at a the vector of presence absence (0/1) and the relevant SNP (e.g. A/G) and see if there is a tendency of the SNP to be with a certain value (e.g. A) when the k-mer is present. 

Yes, each k-mer separately. You can start with a few study cases and see if it directs you to a place in the genome.

**Comment by DuttaAnik** [comment]
Thanks a lot, Yoav. Thanks for your suggestions. Yes, those make complete sense. It is challenging but very interesting. :)
