### ISSUE TITLE
the emma_kinship_kmers problem

### ISSUE THREAD

**Issue by BlueIsTheWarmestColor** [voichek/kmersGWAS#95]
Dear Voichek,

Thanks to your re-compiled build_kmers_table, I've got the kmers_table.table. But when I moved to the emma_kinship_kmers step, something wierd happened. My kmers_table.table file size is 2.3T, containing about 5.5 billion kmers. I don't know if it's because of the file size, the emma_kinship_kmers step has kept on loading without outputing anything else for more than 4 days.  

And when I run the build_kmers_table step, I give the task 32G mem, the job's actual max mem usage was 568.082M.

Here is the step log.
![kinship_log](https://user-images.githubusercontent.com/81240601/120951856-66d46600-c77c-11eb-8acb-fd214eeef44b.PNG)

Looking forward to your advice.

Sincerely,
Simon.

**Comment by voichek** [comment]
Dear Simon,

I am afraid this might take a while to run, I think the kinship is the longest step. At the time I thought of ways to speed this up, but as this is something that you run only once per database I decided not to go into it. It's indeed doesn't require a lot of memory.

If you have a kinship matrix based on SNPs it can be used instead (this is what I actually used in the paper). If you have the SNP table in plink binary file you can create this kinship using `emma_kinship` which should be much faster as you likely have a few order of magnitude less SNPs. 

Your dataset is much larger than anything I used, if this will be a problem for more users I would do this extra optimization at some point. The issue is that it will take me ~2 work days, so I will need to find time for this.

Best,
Yoav

**Comment by BlueIsTheWarmestColor** [comment]
Dear Voichek,

Thanks again for your generous help. And I get some useful results after taking your advice! Thank you so much.

Sincerely,
Simon
